### ISSUE TITLE
Open links with mpv using proxychains for a proxy on linux?

### ISSUE THREAD

**Issue by fliegentoeter** [grmat/play-with#10]
Hello,

does anyone know how to open links not only with mpv but with the "proxychains mpv" command?
I tried using a .desktop file and a bash script but none of them worked for me.
Using Manjaro and still somewhat new to this linux thing, so I don't have a lot of expierience.
Thanks

**Comment by grmat** [comment]
You should in fact be able to solve that with a script. Not in scope of play-with.
