### ISSUE TITLE
Please update your README.md with the supported browser and this add-on installation procedure

### ISSUE THREAD

**Issue by sebma** [grmat/play-with#11]
Hi,

Can you please update your [README.md](../blob/master/README.md) with the supported browser and this add-on installation procedure ?

God bless you.

**Comment by grmat** [comment]
Hi,

this is a Firefox WebExtension. See the linked [AMO](https://addons.mozilla.org/en-US/firefox/addon/play-with/) page to install it. Check [Mozilla Wiki](https://wiki.mozilla.org/Installing_Extensions) for manual installation.
