### ISSUE TITLE
[OUT OF TOPIC] amdgpu-fancontrol

### ISSUE THREAD

**Issue by Aquassarim** [grmat/play-with#14]
Hello grmat.
I apologize for asking here something that matters with amdgpu-fancontrol which is read-only now. I didn't find an other way to contact you...
amdgpu-fancontrol saves my GPU everyday from over heating. Thank you!
However, the script amdgpu-fancontrol produces numerous entries in /var/log/syslog. To avoid that, I have created a variable DEBUG_SYSLOG=false and duplicated your debug function (debug_syslog) while just changing $DEBUG with $DEBUG_SYSLOG
At lines 61, 62 and 63 I have replaced the echo with debug_syslog.
It seems to do the job but since I am not familiar with bash, I wonder if it's correct and I also wonder what $DEBUG || is for at the beginning of line 61.
Thank you for your help and once again excuse me for dealing here with something which has noting to do here.
Aqua

**Comment by grmat** [comment]
`||` is a boolean or operator.

You could create a fork and push your changes, so others could see your changes and you won't have to describe them in prose.

Opening an issue asking shell basics in an unrelated project is something you shouldn't do ever again. I hope that doesn't sound mean, it's honest advice.

Sorry for the late answer, it's not like i didn't want to help you, I wasn't able to.
