### ISSUE TITLE
Compatibility with JW Player with MEDIAL

### ISSUE THREAD

**Issue by grahamperrin** [grmat/play-with#5]
https://mediastream.brighton.ac.uk/Play/1439 for example. The result: 

```text
#EXTM3U
https://mediastream.brighton.ac.uk/Play/1439
```

– does open in VLC media player, but there's no playback. 

<strike>Can you tell, is this an unavoidable penalty of use of Vualto?</strike>

If it helps, from within the source of the page: 

- https://mediastream.brighton.ac.uk/player510.swf?streamer=rtmp://helixstream.brighton.ac.uk/flash&amp;file=20121671_hd.mp4

– results in the _appearance_ of a player, with a playback button, but again there's no playback. 

### Use case

https://mobile.twitter.com/grahamperrin/status/1051005890491506693 – as far as I can tell, no way for content owners to download (and so, edit) their own content. 

### Links

https://www.medial.com/

https://www.jwplayer.com

https://github.com/jwplayer

https://en.wikipedia.org/wiki/JW_Player#Features_and_licensing

> … JW Player supports … Digital rights management (DRM) (in collaboration with Vualto), …

https://www.vualto.com/

**Comment by grahamperrin** [comment]
Oops, I overlooked this (also in the source of the example page): 

- https://mediastream.brighton.ac.uk/flash/20121671_hd.mp4

– which **does** play in the browser (Waterfox 56.2.3) and VLC Media Player. 

So (ignoring my misplaced suspicion re: DRM): 

- please, might _play-with_ gain compatibility with MEDIAL instances such as this?

----

`https://github.com/jwplayer/jwplayer/issues/1826#issuecomment-279824090`

> We don't condone downloading videos from publishers without their permission.

Fair enough, but it's troublesome when a content owner can not _easily_ download his or her own content ;-)

**Comment by grmat** [comment]
Hi Graham,

play-with is really intended to do just one thing, which is linking native software such as VLC, mpv or youtube-dl to media sources that are accessed in a web browser. I don't want to add functionality already present in this programs to play-with.

AFAICT, VLC doesn't have the functionality to find and play JWPlayer embedded media, or find any media embedded in a web page, for this matter. It has to be presented with the direct media URL, which in your case is (as you already found out):

>     * https://mediastream.brighton.ac.uk/flash/20121671_hd.mp4


However, [youtube-dl](https://github.com/rg3/youtube-dl) does have this functionality and I encourage you (and any play-with user, as mentioned on AMO and in the README) to try it out. The page you linked 

> https://mediastream.brighton.ac.uk/Play/1439

works flawlessly with youtube-dl and mpv via play-with.

> ### Use case
> 
> https://mobile.twitter.com/grahamperrin/status/1051005890491506693 – as far as I can tell, no way for content owners to download (and so, edit) their own content.

This is obviously a problem of the platform provider, users should report it to them to find a solution.

In the meantime, downloading the previously published Video with youtube-dl is a functional workaround.

I'm closing this bug, but you can still respond if you need more info.
