### ISSUE TITLE
[request] option to choose preferred resolution

### ISSUE THREAD

**Issue by rismanrp** [grmat/play-with#9]
First off, thank you for your wonderful add on, this helps me a lot! 

I think it would be perfect if there's a simple option to choose a preferred or maximum resolution (at least for youtube). Being able to limit them to e.g. 480p max would be really helpful for people with slow internet, limited data cap, or even slow computer.

**Comment by grmat** [comment]
Hi,

you're not the first one. See answers in #4 and #6

**Comment by rismanrp** [comment]
Hi, thank you for your answer. I found out how to do it.

This is what I did:

~/.config/mpv/mpv.conf
`ytdl-format="bestvideo[height<=?480]+bestaudio/best"`

With this, every time mpv opens a Youtube link (from this add on or any other), it will be maxed out at 480p resolution.

**Comment by grmat** [comment]
Yes, glad it works for you. 

The downside is that this is now your default and chosen every time you use mpv. I don't know how you usually use mpv but you could also look into maintaining different profiles.
